import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "ar" | "en";

export const translations = {
  ar: {
    // Shared
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    delete: "حذف",
    search: "بحث",
    all: "الكل",
    active_env: "بيئة نشطة",
    sys_time: "توقيت النظام المالي",
    close: "إغلاق",
    yes: "نعم",
    no: "لا",
    loading: "جاري تحميل البيانات...",
    error: "خطأ",
    success: "تم بنجاح",
    currency_sar: "ر.س",

    // Sidebar
    platform_name: "المنصة المالية المتكاملة",
    saas_erp_suite: "SaaS ERP Suite",
    current_tenant: "المنشأة الحالية (Tenant)",
    register_new_tenant: "تسجيل منشأة جديدة",
    dashboards_title: "لوحات ومنصات العمل",
    tab_dashboard: "الرئيسية والتحليلات",
    tab_operations: "العمليات والخدمات",
    tab_clients: "العملاء والمؤسسات",
    tab_invoices: "دفتر الفواتير",
    tab_settings: "إعدادات وهُوية الفاتورة",
    tab_expenses: "المصروفات التشغيلية",
    tab_google_sync: "جداول قوقل (Google Sheets)",
    tab_subscriptions: "إدارة الاشتراكات للشركة (SaaS)",
    dark_mode: "الوضع الليلي",
    data_security_iso: "أمان البيانات ومعيار ISO 27001",
    data_security_desc: "تدار الفواتير والأرباح بتفعيل التشفير ومعزل الأمان المتكامل للواجهة الخلفية.",

    // New Tenant Modal
    tenant_modal_title: "تسجيل منشأة / شركة SaaS جديدة",
    tenant_modal_desc: "تقوم هذه الخطوة بإنشاء قاعدة بيانات معزولة بالكامل (Isolated Tenant Schema) لهذه الشركة الجديدة، مما يضمن أمان وخصوصية البيانات وتجنب اختلاط الفواتير والعملاء مع المنشآت الأخرى.",
    tenant_name_label: "اسم الشركة المراد إدارتها *",
    tenant_placeholder: "مثال: شركة التطوير العقاري الخليجية",
    tenant_modal_confirm: "تأكيد وإنشاء الكيان المعزول",

    // Dashboard
    db_title: "نظرة عامة على البيانات المالية",
    db_subtitle: "الرسم والبيانات اللحظية بناءً على العمليات والفواتير المدخلة للشركة الحالية",
    db_isolated_secured: "البيانات معزولة ومحمية بالكامل",
    db_total_revenue: "إجمالي الإيرادات",
    db_liquidity_rate: "معدل السيولة الواردة",
    db_total_costs: "إجمالي التكاليف والمصاريف",
    db_budget_consumption: "مستهلكات الميزانية",
    db_net_profit: "صافي الأرباح التشغيلية",
    db_net_return: "العائد المالي الصافي",
    db_operating_margin: "هامش الربح التشغيلي",
    db_profit_percentage: "نسبة الربح من المبيعات",
    db_paid_settled: "الفواتير المسددة والمحصلة",
    db_deposited_cash: "سيولة تم إيداعها بالحساب",
    db_unpaid_invoices: "مبالغ فواتير مستحقة الدفع",
    db_unreceived_notes: "سندات ذمم غير مستلمة",
    db_overdue_alerts: "ديون متأخرة الدفع وقيد الإنذار",
    db_due_dates_passed: "مواعيد الاستحقاق انتهت",
    db_overdue_title: "الفواتير المتأخرة والذمم المعلقة",
    db_overdue_subtitle: "فواتير لم تسدد وتجاوزت تاريخ الاستحقاق",
    db_no_overdue: "لا توجد فواتير متأخرة حالياً.",
    db_latest_operations: "آخر العمليات والخدمات المسجلة",
    db_latest_ops_subtitle: "أحدث 5 خدمات تشغيلية",
    db_no_operations: "لا توجد عمليات مسجلة",
    db_col_client: "العميل",
    db_col_amount: "المبلغ",
    db_col_due: "الاستحقاق",
    db_col_payment_date: "تاريخ السداد",
    db_col_status: "الحالة",
    db_col_action: "الإجراء",
    db_btn_collect: "تحصيل",
    db_status_paid: "مسددة",
    db_status_unpaid: "غير مسددة",

    // Operations Tab
    op_add_title: "إضافة عملية تشغيلية جديدة",
    op_add_desc: "العملية التشغيلية (مثل: تطوير موقع الكتروني، خدمات استشارية) وبقيمة تكلفتها الفعلية وإيرادها المتوقع.",
    op_service_name_label: "اسم الخدمة / العملية التشغيلية *",
    op_service_placeholder: "مثال: تطوير متجر إلكتروني ذكي",
    op_associated_client: "العميل المرتبط بالخدمة",
    op_select_client: "اختر العميل",
    op_cost_label: "تكلفة إنتاج الخدمة (مصاريف)*",
    op_revenue_label: "الإيراد المطلوب للفاتورة*",
    op_submit_btn: "إضافة الخدمة وتوليد الفاتورة",
    op_log_title: "سجل العمليات التشغيلية والخدمات الفعالة",
    op_search_placeholder: "شريط بحث متقدم بالخدمات والشركات...",
    op_no_ops_match: "لا توجد أي خدمات مسجلة تطابق بحثك حالياً.",
    op_table_col_service: "الخدمة / العملية",
    op_table_col_cost: "التكلفة",
    op_table_col_revenue: "الإيراد",
    op_table_col_profit: "صافي الربح",
    op_table_col_date: "التاريخ",
    op_table_col_action: "الإجراء",

    // Clients Tab
    cli_add_title: "تسجيل عميل جديد",
    cli_add_desc: "إضافة عميل أو مؤسسة لتتمكن من إصدار فواتير ضريبية تابعة له وربطه بالخدمات التشغيلية.",
    cli_name_label: "الاسم الكامل للعميل / الممثل *",
    cli_name_placeholder: "عبدالله الشمري",
    cli_company_label: "المؤسسة / الشركة التابعة",
    cli_company_placeholder: "مؤسسة الأفق",
    cli_phone_label: "رقم الهاتف / الاتصال",
    cli_phone_placeholder: "+966500000000",
    cli_submit_btn: "تأكيد الحفظ",
    cli_list_title: "دليل العملاء والمؤسسات المسجلين",
    cli_search_placeholder: "بحث بالاسم، المنشأة، أو الهاتف...",
    cli_no_records: "لا توجد سجلات تدرج تحت بحثك الحالي.",
    cli_table_col_name: "العميل المستهدف",
    cli_table_col_company: "اسم المنشأة",
    cli_table_col_phone: "رقم الاتصال",

    // Invoices Tab
    inv_title: "قائمة وكشف حساب الفواتير الضريبية",
    inv_search_placeholder: "البحث بكود الفاتورة أو العميل...",
    inv_export_csv: "تصدير الفواتير لملف CSV",
    inv_table_col_id: "كود الفاتورة",
    inv_table_col_client: "المستلم (العميل)",
    inv_table_col_amount: "المبلغ الإجمالي",
    inv_table_col_due: "تاريخ الاستحقاق",
    inv_btn_print: "طباعة وتصدير PDF",
    inv_btn_share: "مشاركة",

    // Settings Tab
    set_vbrand_title: "الهوية والسمة البصرية للفاتورة",
    set_widgets_title: "ترتيب مربعات الإحصائيات (سحب وإفلات)",
    set_widgets_desc: "قم بسحب وإفلات مربعات الإحصائيات (أو استخدام الأسهم المساعدة) لترتيب تسلسل ظهورها في الواجهة الرئيسية للوحة التحكم:",
    set_widget_revenue: "إجمالي الإيرادات الكلية",
    set_widget_costs: "إجمالي التكاليف والمصاريف",
    set_widget_net_profit: "صافي الأرباح التشغيلية",
    set_widget_profit_margin: "هامش الربح التشغيلي",
    set_upload_logo: "تحميل شعار المنشأة (رابط صورة)",
    set_logo_placeholder: "رابط الشعار المخصص",
    set_primary_color: "اللون الأساسي للفاتورة والواجهة",
    set_currency_label: "العملة الرسمية للفاتورة",
    set_save_btn: "حفظ الإعدادات والهوية التجارية",
    set_audit_title: "سجل مراقبة الأحداث والعمليات الأمنية (Audit Log)",
    set_audit_desc: "متابعة الأنشطة المالية والإدارية والتنظيمية للكيان الحالي لضمان الشفافية والمراقبة الدقيقة",
    set_refresh_btn: "تحديث السجل",
    set_audit_search_placeholder: "البحث في سجل الإجراءات أو المستندات...",
    set_audit_category: "تصنيف الحدث:",
    set_cat_all: "الكل",
    set_cat_creation: "الإنشاء والتسجيل",
    set_cat_settings: "تعديل الهوية",
    set_cat_deletion: "عمليات الحذف",
    set_cat_invoice: "تعديل الفواتير",
    set_audit_table_action: "موجز الحدث",
    set_audit_table_details: "تفاصيل الإجراء والمستندات المرتبطة",
    set_audit_table_time: "التاريخ والتوقيت (توقيت محلي)",
    set_audit_table_user: "المستخدم / الفاعل",
    set_audit_empty: "لا توجد أي سجلات أحداث تطابق معايير البحث الحالية.",
    set_audit_loading: "جاري قراءة سجل الأحداث من المخدم الآمن...",
    set_audit_footer: "نظام ERP الآمن لتدقيق العمليات الموحد (System Audit Vault v1.1)",
    set_audit_count_prefix: "عرض",
    set_audit_count_suffix: "جهة حماية مسجلة",

    // Print Modal
    print_options_title: "خيارات تصدير الفاتورة",
    print_options_desc: "قم بتهيِئة خيارات الطباعة وتضمين الملاحظات قبل حفظ الفاتورة كـ PDF.",
    print_notes_label: "الملاحظات أسفل الفاتورة",
    print_notes_placeholder: "أضف شروط الدفع، تفاصيل الحساب البنكي أو شكر خاص للعميل...",
    print_stamp_label: "لون ختم الاعتماد (مُبَطَّن)",
    print_stamp_emerald: "أخضر معتمد",
    print_stamp_indigo: "أزرق رسمي",
    print_stamp_rose: "وردي تنبيهي",
    print_standard_title: "💡 معيار الفوترة الضريبية للمملكة",
    print_standard_desc: "تلتزم الفاتورة بتخطيط هيئة الزكاة والضريبة والجمارك (ZATCA) في السعودية، بما يشمل الرقم الضريبي الموثق والترميز الذكي والـ VAT بنسبة 15%.",
    print_btn_print: "تحميل PDF / طباعة الفاتورة",
    print_btn_share: "مشاركة بيانات الفاتورة",
    print_copied: "تم نسخ البيانات للمشاركة!",
    print_pdf_hint: "اختر حفظ بتنسيق PDF (Save as PDF) من قائمة الطابعات المتاحة لتوليد وتصدير ملف PDF مباشرة بأعلى دقة.",

    // Invoice Document Translation
    doc_tax_invoice: "فاتورة ضريبية مبسطة",
    doc_vat_id: "الرقم الضريبي للمنشأة:",
    doc_invoice_id: "رقم الفاتورة:",
    doc_date_issue: "تاريخ الإصدار:",
    doc_date_due: "تاريخ الاستحقاق:",
    doc_status: "حالة الفاتورة:",
    doc_client_title: "المشتري / عميل الفاتورة",
    doc_service_col: "البيان والخدمة التشغيلية",
    doc_taxable_subtotal: "الخاضع للضريبة (15%)",
    doc_vat_amount: "قيمة الضريبة المضافة (15%)",
    doc_grand_total: "الإجمالي شامل الضريبة المضافة",
    doc_authorized_stamp: "ختم الاعتماد والتوثيق الرقمي",
    doc_certified: "مُعتمد ومحمل رقمياً بموجب نظام التعاملات المالية الموحد للكيانات.",
    doc_unpaid: "قيد الانتظار والدفع",

    // Expenses
    exp_title: "تسجيل وإدارة المصروفات التشغيلية الدورية",
    exp_desc: "تسمح لك هذه الصفحة بمتابعة المصاريف التشغيلية الثابتة والدورية (الإيجار، الاشتراكات، الرواتب، الخدمات) لدعم دقة احتساب صافي الأرباح.",
    exp_add_title: "تسجيل مصروف جديد",
    exp_category_label: "فئة المصروف *",
    exp_category_rent: "إيجار مقرات",
    exp_category_salaries: "رواتب ومكافآت",
    exp_category_office_supplies: "أدوات مكتبية ومستلزمات",
    exp_category_subscriptions: "اشتراكات برمجيات وسحابة",
    exp_category_utilities: "مرافق عامة (كهرباء، ماء، اتصالات)",
    exp_category_marketing: "حملات تسويقية وإعلانات",
    exp_category_other: "مصروفات تشغيلية أخرى",
    exp_amount_label: "قيمة المصروف *",
    exp_frequency_label: "دورية التكرار *",
    exp_freq_weekly: "أسبوعي",
    exp_freq_monthly: "شهري",
    exp_freq_yearly: "سنوي",
    exp_freq_once: "يدوي (مرة واحدة)",
    exp_date_label: "تاريخ الاستحقاق / الدفع *",
    exp_desc_label: "بيان وتفاصيل المصروف",
    exp_desc_placeholder: "مثال: إيجار فرع الرياض الربع السنوي",
    exp_submit_btn: "إدراج وتسجيل المصروف",
    exp_ledger_title: "سجل المصروفات التشغيلية للمنشأة",
    exp_col_category: "الفئة",
    exp_col_amount: "المبلغ",
    exp_col_freq: "التكرار الدورية",
    exp_col_date: "التاريخ",
    exp_col_desc: "البيان والوصف",
    exp_col_action: "الإجراء",
    exp_no_expenses: "لم يتم تسجيل أي مصروفات تشغيلية للمنشأة حالياً.",
    exp_search_placeholder: "تصفية بالبيان والوصف...",
    exp_total_monthly_recurring: "إجمالي العبء الشهري المقدر",

    // Authentication / Login
    auth_welcome_title: "بوابة الوصول الآمن",
    auth_welcome_subtitle: "المنصة المالية المتكاملة ونظام إدارة المنشآت المتعددة المستأجرين",
    auth_benefits_title: "حماية مطلقة لبياناتك ماليًا",
    auth_benefit_isolation: "عزل كامل لبيانات كل شركة (Multi-Tenant Isolation)",
    auth_benefit_firestore: "تشفير سحابي للبيانات باستخدام نوى Firestore المؤمنة",
    auth_benefit_google: "تسجيل دخول موحد آمن وسهل عبر حساب Google",
    auth_sign_in_btn: "تسجيل الدخول الآمن بـ Google",
    auth_sign_out_btn: "تسجيل الخروج",
    auth_logged_in_as: "متصل كـ",
    auth_securing_access: "جاري التحقق من أمان الجلسة...",
  },
  en: {
    // Shared
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    search: "Search",
    all: "All",
    active_env: "Active Env",
    sys_time: "System Financial Time",
    close: "Close",
    yes: "Yes",
    no: "No",
    loading: "Synchronizing databases...",
    error: "Error",
    success: "Success",
    currency_sar: "SAR",

    // Sidebar
    platform_name: "Integrated ERP",
    saas_erp_suite: "SaaS ERP Suite",
    current_tenant: "Current Tenant",
    register_new_tenant: "Register New Tenant",
    dashboards_title: "Workboards & Management",
    tab_dashboard: "Home & Analytics",
    tab_operations: "Operations & Services",
    tab_clients: "Clients & Corporate",
    tab_invoices: "Invoice Ledger",
    tab_settings: "Invoice Settings & Identity",
    tab_expenses: "Operational Expenses",
    tab_google_sync: "Google Sheets",
    tab_subscriptions: "SaaS Subscriptions",
    dark_mode: "Dark Mode",
    data_security_iso: "Secured Data & ISO 27001",
    data_security_desc: "Invoices and profits are fully isolated, encrypted and secure locally and on server.",

    // New Tenant Modal
    tenant_modal_title: "Register New SaaS Tenant Co.",
    tenant_modal_desc: "This step creates a fully isolated database schema for this company, avoiding cross-account leaks of invoices, operations or clients.",
    tenant_name_label: "Company / Tenant Name *",
    tenant_placeholder: "e.g., Gulf Tech Development Ltd",
    tenant_modal_confirm: "Confirm & Build Isolated Tenant",

    // Dashboard
    db_title: "Financial KPI Overview",
    db_subtitle: "Real-time indicators and visualizations from active logs & invoices",
    db_isolated_secured: "Data is isolated and secured",
    db_total_revenue: "Total Revenue",
    db_liquidity_rate: "Active Liquidity",
    db_total_costs: "Total Costs & Expenses",
    db_budget_consumption: "Budget Outflow",
    db_net_profit: "Net Operating Profit",
    db_net_return: "Net Bottomline Return",
    db_operating_margin: "Operating Profit Margin",
    db_profit_percentage: "Sales conversion margin",
    db_paid_settled: "Paid & Settled Invoices",
    db_deposited_cash: "Liquidity deposited in bank",
    db_unpaid_invoices: "Outstanding Invoices",
    db_unreceived_notes: "Unreceived bills",
    db_overdue_alerts: "Overdue & Aging Receivable Alert",
    db_due_dates_passed: "Payment deadlines expired",
    db_overdue_title: "Overdue Invoices",
    db_overdue_subtitle: "Pending invoices exceeding due date parameters",
    db_no_overdue: "No overdue accounts presently.",
    db_latest_operations: "Operational Log Feed",
    db_latest_ops_subtitle: "Latest 5 operations",
    db_no_operations: "No operations indexed.",
    db_col_client: "Client",
    db_col_amount: "Amount",
    db_col_due: "Due Date",
    db_col_payment_date: "Paid On",
    doc_unpaid: "Outstanding for settlement",
    db_col_status: "Status",
    db_col_action: "Action",
    db_btn_collect: "Collect",
    db_status_paid: "Paid",
    db_status_unpaid: "Unpaid",

    // Operations Tab
    op_add_title: "Record New Operation",
    op_add_desc: "Register an operation (e.g., tech build, consultancy) with defined cost/expense and projected billing.",
    op_service_name_label: "Service / Operation Name *",
    op_service_placeholder: "e.g., E-Commerce Platform Build",
    op_associated_client: "Target Client Portfolio",
    op_select_client: "Select customer client",
    op_cost_label: "Service Raw production Cost*",
    op_revenue_label: "Expected Billable Revenue*",
    op_submit_btn: "Commit Service & Generate Invoice",
    op_log_title: "Active Operational log Ledger",
    op_search_placeholder: "Advanced filter for services and customers...",
    op_no_ops_match: "No active services match search parameters.",
    op_table_col_service: "Service Description",
    op_table_col_cost: "Production Cost",
    op_table_col_revenue: "Gross Billing",
    op_table_col_profit: "Operational Profit",
    op_table_col_date: "Entry Date",
    op_table_col_action: "Action",

    // Clients Tab
    cli_add_title: "Onboard Client Entity",
    cli_add_desc: "Onboard customers or firms to issue simplified tax-compliant invoices and track operations.",
    cli_name_label: "Client Representative *",
    cli_name_placeholder: "John Doe",
    cli_company_label: "Affiliate Organization/Company",
    cli_company_placeholder: "Aero Logistics Group",
    cli_phone_label: "Phone / Contact",
    cli_phone_placeholder: "+966500000000",
    cli_submit_btn: "Confirm & Add Client",
    cli_list_title: "Verified Customers & Entities",
    cli_search_placeholder: "Filter by title, company, phone...",
    cli_no_records: "No registered client fits criteria active.",
    cli_table_col_name: "Customer Lead",
    cli_table_col_company: "Corporate Group",
    cli_table_col_phone: "Contact Line",

    // Invoices Tab
    inv_title: "Tax Invoice Book & Ledgers",
    inv_search_placeholder: "Search by Invoice Reference or Client name...",
    inv_export_csv: "Export Book to CSV",
    inv_table_col_id: "Reference No",
    inv_table_col_client: "Primary Recipient",
    inv_table_col_amount: "Gross Amount",
    inv_table_col_due: "Ultimate Due",
    inv_btn_print: "PDF / Print",
    inv_btn_share: "Share Detail",

    // Settings Tab
    set_vbrand_title: "Visual Brand Identity config",
    set_widgets_title: "Statistics KPI Widgets Order (Drag & Drop)",
    set_widgets_desc: "Drag and drop the KPI layouts below (or use the helper arrows) to customize their display sequence on the main Dashboard page:",
    set_widget_revenue: "Total Gross Inflow / Revenue",
    set_widget_costs: "Total Outflow / Cost",
    set_widget_net_profit: "Net Operating Profit",
    set_widget_profit_margin: "Operating Profit Margin %",
    set_upload_logo: "Enterprise Logo (Image URL)",
    set_logo_placeholder: "Valid Image url here",
    set_primary_color: "Primary Brand Interface Theme",
    set_currency_label: "System Functional Currency",
    set_save_btn: "Save All Settings & Identity",
    set_audit_title: "Event Auditing System Log (Audit Trail)",
    set_audit_desc: "Verify financial, organizational, and structural operations of current environment.",
    set_refresh_btn: "Refresh Trail",
    set_audit_search_placeholder: "Filter actions or logs...",
    set_audit_category: "Classification filter:",
    set_cat_all: "All Logs",
    set_cat_creation: "Creates & Inputs",
    set_cat_settings: "Identity Configs",
    set_cat_deletion: "Safe Deletes",
    set_cat_invoice: "Invoice Auditing",
    set_audit_table_action: "Category action summary",
    set_audit_table_details: "Action audit statement & references",
    set_audit_table_time: "Time (System localized)",
    set_audit_table_user: "Audit Actor",
    set_audit_empty: "No auditing entry matches current queries.",
    set_audit_loading: "Consulting with Audit trail API...",
    set_audit_footer: "Secure Audit Vault engine active v1.1",
    set_audit_count_prefix: "Displaying",
    set_audit_count_suffix: "audit actions logged",

    // Print Modal
    print_options_title: "Billing PDF Config",
    print_options_desc: "Preset printing values, colors, or custom legal headers before building the draft.",
    print_notes_label: "Custom Legal Note / Footer disclaimer",
    print_notes_placeholder: "Define IBAN values, custom warranty terms, or corporate thanks...",
    print_stamp_label: "Authorized Stamp color",
    print_stamp_emerald: "Emerald Certified",
    print_stamp_indigo: "Indigo Corporate",
    print_stamp_rose: "Rose Warning",
    print_standard_title: "💡 GCC / ZATCA Billing Integration",
    print_standard_desc: "Compliance with Saudi Zakat Tax and Customs Authority requirements, utilizing digital elements and standard 15% VAT calculation.",
    print_btn_print: "Compile & Print PDF",
    print_btn_share: "Share Invoice Ledger Meta",
    print_copied: "Meta values copied!",
    print_pdf_hint: "Choose 'Save as PDF' from your local print target dropdown list to store files permanently.",

    // Invoice Document Translation
    doc_tax_invoice: "Simplified Tax Invoice",
    doc_vat_id: "Corporate TAX ID:",
    doc_invoice_id: "Reference No:",
    doc_date_issue: "Date Issued:",
    doc_date_due: "Ultimate Due:",
    doc_status: "Payment Status:",
    doc_client_title: "Recipient / Invoice Purchaser",
    doc_service_col: "Billing Line Description",
    doc_taxable_subtotal: "Taxable Base Balance (15% VAT)",
    doc_vat_amount: "Added Value Tax (15% VAT)",
    doc_grand_total: "Invoice Total (Inc. VAT)",
    doc_authorized_stamp: "Digital Stamps Security",
    doc_certified: "Verified, sealed, and signed under unified GCC electronic billing regulations.",

    // Expenses
    exp_title: "Operational & Recurring Expenses Ledger",
    exp_desc: "Register recurring fixed outlays (rent, salaries, subscriptions, utilities) to fine-tune dashboard bottomline net operating profit calculations.",
    exp_add_title: "Onboard New Expense Instance",
    exp_category_label: "Expense Category *",
    exp_category_rent: "Office Rent",
    exp_category_salaries: "Salaries & Rewards",
    exp_category_office_supplies: "Office Supplies",
    exp_category_subscriptions: "Software & Cloud Subscriptions",
    exp_category_utilities: "Utilities (Power, Water, Telecoms)",
    exp_category_marketing: "Marketing Campaigns",
    exp_category_other: "Other Operational Expense",
    exp_amount_label: "Amount *",
    exp_frequency_label: "Recurrence Frequency *",
    exp_freq_weekly: "Weekly",
    exp_freq_monthly: "Monthly",
    exp_freq_yearly: "Yearly",
    exp_freq_once: "One-time / Manual",
    exp_date_label: "Settle/Due Date *",
    exp_desc_label: "Remarks / Statement",
    exp_desc_placeholder: "e.g., Q1 Riyadh Co-working Space rent",
    exp_submit_btn: "Commit Expense Entry",
    exp_ledger_title: "Active Rent & Operating Expense Ledger",
    exp_col_category: "Category",
    exp_col_amount: "Amount",
    exp_col_freq: "Recurrence",
    exp_col_date: "Date",
    exp_col_desc: "Statement Description",
    exp_col_action: "Action",
    exp_no_expenses: "No active operational expenses onboard presently for this workspace.",
    exp_search_placeholder: "Filter by remarks or details...",
    exp_total_monthly_recurring: "Total Estimated Monthly Burden",

    // Authentication / Login
    auth_welcome_title: "Secure Access Portal",
    auth_welcome_subtitle: "Integrated ERP and Multi-Tenant SaaS Management Platform",
    auth_benefits_title: "Uncompromising Financial Data Security",
    auth_benefit_isolation: "Multi-Tenant Isolation for complete company data security",
    auth_benefit_firestore: "Cloud data encryption using Firestore Secure Cores",
    auth_benefit_google: "Secure and seamless single sign-on with your Google Account",
    auth_sign_in_btn: "Secure Sign in with Google",
    auth_sign_out_btn: "Sign Out",
    auth_logged_in_as: "Signed in as",
    auth_securing_access: "Securing access channel...",
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.ar) => string;
  dir: "rtl" | "ltr";
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("erp_lang") as Language) || "ar";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("erp_lang", lang);
  };

  const t = (key: keyof typeof translations.ar): string => {
    return translations[language][key] || translations["ar"][key] || String(key);
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
